### ISSUE TITLE
Teuchos:  How to properly input and validate a vector of parameters?

### ISSUE THREAD

**Issue by palmerb4** [trilinos/Trilinos#11937]
@trilinos/teuchos

## Question
Hi Teuchos team, 

In YAML files it's common to have a vector of parameters such as the following, where each field has the same parameters but the total number of input fields is unknown until the file is parsed.
```
fields:
  - name: force
    dimension: 3
  - name: velocity
    dimension: 3
  - name: pressure
    dimension: 1
```
My question is how to properly input and validate such a parameter list?

Based on existing Teuchos examples, it appears like the current paradigm is to rewrite this as sub-lists:
```
fields:
  count: 3
  field_0:  
    name: force
    dimension: 3
  field_1:    
    name: velocity
    dimension: 3
  field_2:
    name: pressure
    dimension: 1
```
But what I have yet to figure out is how to validate such a parameter list using validateParameters or validateParametersAndSetDefaults. Is there some existing validator that can handle this or some trick that I'm missing? 

Thanks for the help!
Bryce
