### ISSUE TITLE
Teuchos parser not handling commas in strings without quotes

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#1801]
@ibaned as promises, here is the next issue.

Items like
```
Range:
  X: -1.0, 1.0

foo:
  emotions: happy_sad, indifferent
  
```
are not parsing
```
*********** Caught Exception: Begin Error Report ***********
error: Parser failure at line 49 column 32 of Particle_interactions.yaml
      eblock-0_0: ES_POTENTIAL,E1
                              ^
Expected one of {NEWLINE}
Got: ,
Parser was in state 94
```

If I quote the expression it parses, I'm getting a new error and dogging that down now

@rppawlo This is the next stopping block,
